// AUTO-GENERATED by scripts/generate-reel-videos.js — do not edit by hand.
// Edit utils/reel-videos.manifest.json instead, then re-run
// `npm run gen:reel-videos` (or `npm start`).

import { media, type MediaSource } from '../lib/media';

const reelVideos: MediaSource[] = [
  media('reel-videos/3-simple-mistakes-you-must-avoid-with-your-breakfast-ayurved.mp4'),
  media('reel-videos/chris-williamson-born-october-5-1988-is-a-british-podcast-ho.mp4'),
  media('reel-videos/claim-it-comment-888-to-rewire-your-reality-to-supernatural.mp4'),
  media('reel-videos/keep-it-private-until-its-permanent-usahealth-wellness-usa-n.mp4'),
  media('reel-videos/motivational-quotes-1.mp4'),
  media('reel-videos/motivational-quotes-2.mp4'),
  media('reel-videos/people-give-up-right-before-they-get-what-theyve-always-want.mp4'),
  media('reel-videos/podcast.mp4'),
  media('reel-videos/the-same-energy-that-creates-sunsets-oceans-forests.mp4'),
  media('reel-videos/the-world-will-be-as-you-see-it-morningmeditation-manifest-p.mp4'),
  media('reel-videos/type-heal-and-youll-get-my-body-healing-bundle-follow-first.mp4'),
];

export default reelVideos;
